### ISSUE TITLE
怎么参与贡献?

### ISSUE THREAD

**Issue by rainbowflesh** [RSPIC/RWR-HellDivers-Mod#1]
以前给少前 mod 加过内容, 我还可以做本地化.
PR 有没有什么约定或者范式, 或者讨论组?

**Comment by RSPIC** [comment]
暂时还没有考虑，我也是刚接触github和做这个mod，组织多人协作以及考虑奖赏、贡献什么的还不成熟。后面会建立一个制作群讨论组，目前打算完成mod的主要目标（完善cyborgs和superearth阵营，能打起来）后再考虑这个。

**Comment by RSPIC** [comment]
交流群已建立 ：498520233
