### ISSUE TITLE
[bug] duplicate or missing sound resources

### ISSUE THREAD

**Issue by rainbowflesh** [RSPIC/RWR-HellDivers-Mod#5]
Level 2 meaning missing or duplicated sound.
TODO: fix it.

- dbs2_magazine_in.wav
- - hd_cycle_in_01.wav

- hd_dryfire.wav
- - hd_p6_gunslinger_dryfire.wav
- - hd_p2_peacemaker_dryfire.wav

- hd_sg225_breaker_fire_01.wav
- - double_freedom_fire.wav

- hd_p2_peacemaker_fire.wav
- - hd_smg_fire1.wav

**Comment by RSPIC** [comment]
删除：
+ dbs2_magazine_in
+ hd_p6_gunslinger_dryfire
+ hd_p2_peacemaker_dryfire
删除文件用对应文件代替

保留：
+ hd_sg225_breaker_fire_01
+ hd_p2_peacemaker_fire
保留文件待后续同名文件替换
